insights = {
    "BCA-Artificial Intelligence and Data Analytics (BCA-AIDA)": {
        "insight": "1. AI Integration: BCA programs will integrate AI courses into their curriculum, providing students with foundational knowledge and practical skills in machine learning, neural networks, and AI applications.\n2. Data Analytics Emphasis: There will be a strong emphasis on data analytics within BCA programs, equipping students with the ability to analyze and derive insights from large datasets using statistical methods and data visualization techniques.\n3. Practical Projects: BCA students will engage in practical projects that apply AI and data analytics techniques to real-world problems, gaining hands-on experience and building a portfolio of projects to showcase their skills to potential employers.\n4. Industry Partnerships: BCA programs will form partnerships with industry leaders in AI and data analytics, providing students with opportunities for internships, industry projects, and networking events to facilitate their transition into the workforce.\n5. Interdisciplinary Approach: BCA programs will adopt an interdisciplinary approach, integrating AI and data analytics concepts with other areas such as business, finance, healthcare, and social sciences to address complex challenges and opportunities in various domains.",
        "graph": "static/graphs/BCA-AIDA.PNG"
    },
    "BCA-Artificial Intelligence and Machine Learning (BCA-AIML)": {
        "insight": "1. AIML Integration: The BCA program integrates AIML courses to provide students with knowledge and skills in machine learning and AI applications.\n2. Practical Training: Focusing on real-world topics allows students to develop a deeper understanding by applying AIML techniques to real-world problems.\n3. Data Science Course – Covering data processing and predictive modeling, students learn how to analyze data sets and extract useful information.\n4. Ethical Practice of AI: Students will understand ethical considerations in AI development to ensure responsible and transparent solutions.\n5. Industry Work: We offer internships and programs by partnering with industry leaders to expose students to AIML applications in the world.\n6. Career Ready: Students will be prepared for careers in data science, machine learning engineering, and AI research with the ability to solve complex problems and drive innovation.",
        "graph": "static/graphs/BCA-AIML.PNG"
    },
    "BCom-Ecommerce & Retail Managment": {
         "insight": "1. Rapid Growth in E-commerce Sector: The job market for graduates in E-commerce & Retail Management is expected to witness significant growth due to the rapid expansion of the e-commerce industry.\n2. Demand for Digital Marketing Experts: With businesses increasingly focusing on online presence and customer engagement, there will be a high demand for professionals skilled in digital marketing strategies.\n3. Omnichannel Retailing Skills: Graduates with expertise in omnichannel retailing, including online, mobile, and brick-and-mortar retail integration, will be sought after by retailers aiming for seamless customer experiences.\n4. Data Analytics for Business Insights: Proficiency in data analytics tools and techniques will be crucial for analyzing consumer behavior, optimizing sales strategies, and making data-driven business decisions.\n5. Supply Chain Optimization: Knowledge of supply chain management and logistics will be valuable for graduates to ensure efficient inventory management and timely order fulfillment in the e-commerce ecosystem.",
        "graph": "static/graphs/BCOM-ERM.png"
    },
    "Bachelor of Business Administration (BBA)": {
        "insight": "1. Technology Integration: The BBA program incorporates technology-focused courses to prepare students with literacy and proficiency in business analytics tools and platforms.\n2. Data Action Decision Making: By focusing on data analysis and interpretation, students can use big data to make decisions while driving business strategies.\n3. Digital Marketing Education - The BBA program provides expertise in digital marketing covering topics such as SEO, social media marketing, and online advertising to meet the needs of the digital market.\n4. E-Commerce and Entrepreneurship: Students learn about e-commerce trends and strategies, as well as the entrepreneurial skills needed to start and run an online business.\n5. Industry Partnerships: Collaborate with industry partners to bridge the gap between academia and the corporate world by providing students with internships, career programs, and internship opportunities.\n6. Global Business Perspective: The BBA program offers a global business perspective, preparing students to navigate global markets and cultural differences in an interconnected world. knowledge, skills, and thinking. Businesses and entrepreneurs must succeed in the digital age.",
        "graph": "static/graphs/BBA.PNG"
    },
    "Bachelor of Business Administration with Data  Analytics (BBA-DA)": {
        "insight": "1. Data Analytics Integration: BBA programs incorporate data analytics courses to teach students how to collect, analyze, and interpret data for informed business decisions.\n2. Business Intelligence Tools: Students learn to use tools for data visualization and predictive analytics, enabling them to extract insights from data.\n3. Quantitative Analysis Skills: Emphasis is placed on understanding statistical methods and hypothesis testing for deriving meaningful conclusions from data.\n4. Strategic Decision Making: BBA programs teach students to use data-driven insights for strategic decision making, fostering critical thinking in a business context.\n5. Industry-Relevant Projects: Students apply data analytics techniques to real-world business scenarios, gaining practical experience through projects and case studies.\n6. Ethical Data Practices: Programs address ethical considerations in data analytics, stressing the importance of privacy and security in handling data.",
        "graph": "static/graphs/BBA-DA.PNG"
    },
    "Bachelor of Commerce (BCom)": {
        "insight": "1. Digital Transformation: BCom programs will evolve to incorporate more courses on digital skills such as data analysis, e-commerce management, and digital marketing, reflecting the increasing importance of technology in the business world.\n2. Data Analytics Integration: There will be a greater emphasis on data analytics and business intelligence, with BCom students learning how to analyze large datasets to derive actionable insights for strategic decision-making.\n3. Globalization Focus: BCom programs will expand their focus on globalization and international business, offering courses on global supply chain management, cross-cultural communication, and international finance to prepare students for careers in a globalized economy.\n4. Sustainability and Ethics: There will be a growing emphasis on sustainability and ethics in business, with BCom programs incorporating courses on corporate social responsibility, ethical leadership, and sustainable business practices to address pressing environmental and social issues.\n5. Entrepreneurship Support: BCom programs will provide more support for entrepreneurship and innovation, offering courses on business planning, startup management, and venture capital to nurture the next generation of business leaders and innovators.",
        "graph": "static/graphs/BCOM.PNG"
    },
    "Bachelor of Commerce with Honours (BCom-HON)": {
        "insight": "1. Specialized Curriculum Expansion: BCom Honours programs will offer advanced courses in Financial Analysis, Marketing Strategy, and Corporate Governance to provide students with specialized expertise.\n2. Advanced Data Analytics Integration: master advanced statistical techniques, predictive modeling, and data visualization tools for complex business data analysis.\n3. Internationalization Initiatives: BCom Honours will focus on global internships, exchange programs, and cross-cultural learning to prepare students for the global marketplace.\n4. Ethical Leadership Development: Emphasis will be placed on ethical decision-making, corporate social responsibility, and sustainable business practices to nurture ethical leadership qualities.\n5. Entrepreneurship and Innovation Support: Enhanced support for entrepreneurship will include mentorship programs, incubator spaces, and funding opportunities to foster innovation among students.",
        "graph": "static/graphs/BCOMHONS.png"
    },
    "Bachelor of Computer Applications (BCA)": {
        "insight": "1. Advanced AI and Data Analytics: BCA programs will offer advanced courses in AI and data analytics to meet industry demands.\n2. Interdisciplinary Integration: Integration with other fields like healthcare and finance will provide practical applications.\n3. Industry Collaboration: Strengthened ties with industry for internships and projects will enhance practical learning.\n4. Ethical AI Education: Students will learn about the ethical implications of AI technologies.\n5. Entrepreneurship Focus: BCA programs will foster entrepreneurship through support services and courses, encouraging innovation.",
        "graph": "static/graphs/BCA.PNG"
    },
    "Bachelor of Dental Surgery(BDS)": {
        "insight": "1. Technological Integration: BDS programs will integrate advanced technologies like 3D printing, CAD/CAM, and virtual reality for enhanced diagnosis, treatment planning, and patient care.\n2. Interdisciplinary Collaboration: Collaboration with other healthcare disciplines such as medicine, engineering, and psychology will lead to holistic patient care approaches and innovative treatment methodologies.\n3. Specialization Expansion: There will be an expansion of specialized fields within dentistry, such as orthodontics, endodontics, and periodontics, to meet the diverse needs of patients and address evolving dental health challenges.\n4. Global Health Initiatives: BDS programs will focus on global health initiatives, providing students with opportunities for international outreach programs, volunteer work, and research collaborations to address oral health disparities worldwide.\n5. Tele-dentistry Adoption: The adoption of tele-dentistry will enable remote consultations, patient monitoring, and education, improving access to dental care in underserved areas and facilitating continuity of care during emergencies.",
        "graph": "static/graphs/BDS.PNG"
    },
    "Bachelor of Medical Laboratory Technology (BMLT)": {
        "insight": "1. Technological Advancements: BMLT programs will incorporate cutting-edge technologies such as automated analyzers, molecular diagnostics, and point-of-care testing devices, enhancing laboratory efficiency and diagnostic accuracy.\n2. Specialization Opportunities: There will be an increase in specialization opportunities within BMLT, including fields such as clinical biochemistry, microbiology, hematology, and immunology, catering to the diverse needs of healthcare facilities.\n3. Interdisciplinary Collaboration: Collaboration with other healthcare disciplines like medicine, nursing, and pharmacy will lead to multidisciplinary approaches in laboratory diagnostics and patient care, fostering better health outcomes.\n4. Quality Assurance Focus: BMLT programs will emphasize quality assurance measures, including accreditation standards, proficiency testing, and continuous quality improvement initiatives, ensuring high standards of laboratory practice and patient safety.\n5. Research and Innovation: Increased focus on research and innovation will drive advancements in laboratory techniques, diagnostic methodologies, and treatment modalities, contributing to the advancement of medical science and patient care.",
        "graph": "static/graphs/BMLT.PNG"
    },
    "Bachelor of Medicine, Bachelor of Surgery (MBBS)": {
        "insight": "1. Integration of Digital Health Technologies: MBBS programs will integrate digital health technologies such as telemedicine, electronic health records (EHRs), and medical imaging AI for more efficient patient care.\n2. Interdisciplinary Training: Collaboration with other healthcare disciplines like nursing, pharmacy, and public health will foster interdisciplinary training.\n3. Global Health Focus: MBBS programs will emphasize global health initiatives, providing opportunities for international medical electives, research collaborations.\n4. Patient-Centered Care: There will be a greater emphasis on patient-centered care, with MBBS programs integrating communication skills, cultural competence, and ethical principles into the curriculum to ensure compassionate and holistic patient care.\n5. Continued Professional Development: MBBS programs will support lifelong learning and professional development through continuing medical education (CME) programs, mentorship opportunities, and career guidance to empower graduates to stay updated with the latest medical advancements and best practices throughout their careers.",
        "graph": "static/graphs/MBBS.PNG"
    },
    "Bachelor of Pharmacy (BPHARMA)": {
        "insight": "1. Technology Integration: Incorporation of cutting-edge technologies like personalized medicine and biopharmaceuticals to revolutionize drug discovery and delivery.\n2. Clinical Pharmacy Emphasis: Focus on medication therapy management and patient-centered care for optimal therapeutic outcomes.\n3. Interdisciplinary Collaboration: Collaborations with medicine, nursing, and public health to facilitate holistic patient management.\n4. Regulatory Compliance: Priority on adhering to Good Manufacturing Practice (GMP) standards and pharmacoeconomic principles for product safety and efficacy.\n5. Innovation and Research: Increased emphasis on pharmaceutical research to drive advancements in drug development and formulation.",
        "graph": "static/graphs/BPHARMA.PNG"
    },
    "Bachelor of Physiotherapy (BPT)": {
        "insight": "1. Advanced Techniques Integration: BPT programs will integrate advanced physiotherapy techniques like manual therapy and therapeutic exercises to enhance patient rehabilitation.\n2. Specialization Opportunities: Students will have more specialization options such as sports physiotherapy and neurorehabilitation to address diverse patient needs.\n3. Interdisciplinary Collaboration: Collaboration with orthopedics, neurology, and sports medicine will enable comprehensive patient care approaches.\n4. Technology Adoption: Adoption of wearable devices and tele-rehabilitation platforms will improve therapy effectiveness and personalization.\n5. Community Outreach Initiatives: BPT programs will focus on community outreach, offering free or low-cost services to underserved populations, promoting overall health and well-being.",
        "graph": "static/graphs/BPT.PNG"
    },
    "Bachelor of Science(Agriculture)": {
        "insight": "1. Technological Advancements: BSc Agriculture programs will integrate advanced technologies such as precision farming, drones, and biotechnology to improve crop yield and sustainability.\n2. Specialization Opportunities: There will be an increase in specialization options within BSc Agriculture, including fields such as agronomy, horticulture, and agricultural economics, to cater to diverse agricultural needs and interests.\n3. Interdisciplinary Collaboration: Collaboration with other disciplines such as environmental science, economics, and engineering will enable interdisciplinary approaches to address complex agricultural challenges and promote sustainable practices.\n4. Entrepreneurship and Innovation: BSc Agriculture programs will foster entrepreneurship and innovation by providing support for agribusiness startups, research opportunities, and hands-on training in farm management and agricultural technology.\n5. Global Agriculture Focus: Emphasis on global agriculture issues such as food security, climate change, and sustainable development will prepare graduates to contribute to agricultural solutions on a global scale.",
        "graph": "static/graphs/AGRI.PNG"
    },
    "Bachelor of Science(Nursing)": {
        "insight": "1. Growing Demand for Nurses: The job market for nurses is projected to expand steadily, driven by factors such as population aging, increased healthcare access, and advances in medical technology.\n2. Specialized Nursing Roles: There will be a rise in demand for specialized nursing roles in areas such as critical care, oncology, and geriatrics, offering opportunities for career advancement and higher salaries.\n3. Emphasis on Preventive Care: With a shift towards preventive healthcare measures, nurses will play a vital role in health promotion, disease prevention, and patient education.\n4. Technological Integration in Nursing: Nurses will need to adapt to technological advancements in healthcare, including electronic health records (EHRs), telemedicine, and medical robotics, enhancing patient care delivery.\n5. Global Nursing Opportunities: The demand for nurses will extend beyond local borders, with opportunities for international nursing practice, travel nursing, and humanitarian missions."
        ,"graph": "static/graphs/BSN.png"
    },
    "CSE-Artificial Intelligence and Data Science (AIDS)": {
        "insight": "1. Booming AI and Data Science Job Market: The field of AI and data science is experiencing rapid growth, with increasing demand for professionals skilled in machine learning, data analysis, and AI-driven solutions.\n2. Industry Applications Across Sectors: AI and data science techniques are being applied across various industries, including healthcare, finance, retail, and cybersecurity, creating diverse job opportunities for graduates.\n3. Emphasis on Data Privacy and Ethics: With growing concerns around data privacy and ethics, there will be a need for professionals well-versed in ethical AI principles, responsible data handling, and regulatory compliance.\n4. Continuous Learning and Upskilling: Given the evolving nature of AI technologies, lifelong learning and upskilling will be essential for professionals to stay competitive in the job market and adapt to emerging trends.\n5. Collaboration with Interdisciplinary Fields: AI and data science professionals will collaborate with experts from diverse fields such as biology, psychology, and sociology to address complex societal challenges and drive innovation."
,        "graph": "static/graphs/AIDS.PNG"
    },
    "CSE-Artificial Intelligence and Machine Learning (AIML)": {
        "insight": "1. Surge in AI and Machine Learning Adoption: The widespread adoption of AI and machine learning technologies across industries is fueling demand for professionals skilled in algorithm development, deep learning, and neural networks.\n2. Automation and Job Transformation: AI and machine learning will automate routine tasks while creating new job roles that require human oversight, domain expertise, and creativity.\n3. Integration with IoT and Robotics: AI and machine learning techniques will be integrated with IoT devices and robotics systems, leading to advancements in autonomous vehicles, smart homes, and industrial automation.\n4. Ethical AI Implementation: There will be a growing emphasis on ethical AI development practices, fairness, transparency, and accountability to mitigate biases and ensure responsible AI deployment.\n5. AI-Powered Healthcare Solutions: AI and machine learning will revolutionize healthcare delivery, with applications in medical imaging, disease diagnosis, personalized treatment planning, and drug discovery."
,        "graph": "static/graphs/AIML.PNG"
    },
    "CSE-Cyber Security (CY)": {
        "insight": "1. Escalating Cyber Threats: The increasing frequency and sophistication of cyber-attacks will drive demand for cybersecurity professionals skilled in threat detection, incident response, and risk mitigation.\n2. Compliance and Regulatory Focus: Organizations will prioritize compliance with data protection regulations such as GDPR, CCPA, and HIPAA, creating opportunities for cybersecurity specialists with expertise in regulatory compliance.\n3. Cybersecurity Automation and AI: Automation and AI technologies will be leveraged to enhance cybersecurity operations, including threat intelligence, malware detection, and security orchestration.\n4. Skills Shortage and Talent Gap: The cybersecurity industry will face a shortage of skilled professionals, leading to competitive salaries, job security, and ample career growth opportunities for qualified candidates.\n5. Emphasis on Cloud Security: With the widespread adoption of cloud computing, there will be a need for cybersecurity professionals proficient in securing cloud-based infrastructure, applications, and data."
,        "graph": "static/graphs/CY.PNG"
    },
    "CSE-Data Science (DS)": {
        "insight": "1. Data-Driven Decision Making: The demand for data scientists will continue to grow as organizations seek to harness the power of data for informed decision-making, predictive analytics, and business optimization.\n2. Industry Applications Across Sectors: Data science techniques are applicable across diverse industries, including finance, healthcare, marketing, and entertainment, offering varied career opportunities for data science professionals.\n3. Interdisciplinary Skillset: Data scientists will need a multidisciplinary skillset encompassing statistics, programming, machine learning, and domain expertise to effectively analyze complex datasets and derive actionable insights.\n4. Focus on Data Privacy and Security: With increasing concerns around data privacy and security, data scientists will be required to adhere to ethical data practices, regulatory compliance, and robust cybersecurity measures.\n5. Lifelong Learning and Skill Enhancement: Continuous learning and skill enhancement will be essential for data scientists to keep pace with evolving technologies, tools, and methodologies in the field of data science."
,        "graph": "static/graphs/DS.PNG"
    },
    "CSE-Internet of Things (IOT)": {
        "insight": "1. Proliferation of IoT Devices: The IoT industry will experience exponential growth, driven by the proliferation of connected devices, smart sensors, and IoT-enabled infrastructure across various sectors.\n2. Integration with AI and Edge Computing: IoT systems will increasingly leverage AI algorithms and edge computing capabilities to process real-time data, extract actionable insights, and enable autonomous decision-making.\n3. Focus on Data Security and Privacy: With the massive volume of data generated by IoT devices, there will be a heightened focus on data security, encryption, and privacy-preserving techniques to mitigate cyber threats and safeguard sensitive information.\n4. Industry-Specific IoT Solutions: IoT technology will be tailored to specific industry verticals, including healthcare, agriculture, manufacturing, and smart cities, to address unique challenges and optimize operational efficiency.\n5. Career Opportunities in IoT Ecosystem: The IoT ecosystem will offer diverse career opportunities for professionals skilled in IoT architecture, embedded systems development, wireless networking, and IoT platform management."
,        "graph": "static/graphs/IOT.PNG"
    },
    "Civil Engineering (CE)": {
        "insight": "1. Infrastructure Development Projects: Civil engineers will play a critical role in designing, constructing, and maintaining infrastructure projects such as roads, bridges, airports, and water supply systems to support urbanization and economic growth.\n2. Sustainable Construction Practices: There will be a growing emphasis on sustainable construction practices, including green building design, renewable energy integration, and waste reduction, to mitigate environmental impact and conserve natural resources.\n3. Smart Cities and Urban Planning: Civil engineers will contribute to the development of smart cities through urban planning, transportation optimization, and the implementation of IoT technologies to enhance livability, sustainability, and resilience.\n4. Resilience to Climate Change: Civil engineers will focus on designing infrastructure resilient to climate change impacts, such as rising sea levels, extreme weather events, and flooding, to ensure long-term durability and safety.\n5. Embrace of Digital Technologies: The adoption of digital technologies such as Building Information Modeling (BIM), Geographic Information Systems (GIS), and drones will streamline project management, improve efficiency, and enhance collaboration in the civil engineering industry."
,        "graph": "static/graphs/CE.PNG"
    },
    "Electrical and Computer Engineering (ECE)": {
        "insight": "1. Advancements in Electronics and Communication: Electrical and computer engineers will drive innovations in electronics, telecommunications, and wireless networking technologies, enabling faster data transmission, connectivity, and IoT integration.\n2. Renewable Energy Solutions: There will be a shift towards renewable energy sources such as solar, wind, and hydroelectric power, driving demand for electrical engineers skilled in energy storage systems, grid integration, and smart grid technologies.\n3. Autonomous Systems and Robotics: ECE professionals will design and develop autonomous systems, drones, and robotics applications for various industries, including agriculture, manufacturing, and healthcare, to enhance productivity and efficiency.\n4. Cyber-Physical Systems Integration: The integration of cyber-physical systems (CPS) will enable seamless interaction between digital and physical components, leading to advancements in smart transportation, healthcare monitoring, and industrial automation.\n5. Focus on Cybersecurity: With the proliferation of connected devices and IoT ecosystems, there will be an increased focus on cybersecurity measures to protect critical infrastructure, data integrity, and privacy."
,        "graph": "static/graphs/ECE.PNG"
    },
    "Electrical and Electronics Engineering (EEE)": {
        "insight": "1. Renewable Energy Revolution: Electrical and electronics engineers will lead the transition towards renewable energy sources such as solar, wind, and hydroelectric power through innovations in energy conversion, storage, and grid integration technologies.\n2. Electrification of Transportation: There will be a shift towards electric vehicles (EVs) and sustainable transportation systems, driving demand for engineers skilled in battery technology, electric motor design, and charging infrastructure development.\n3. Smart Grid and Energy Management: EEE professionals will develop smart grid solutions, energy management systems, and IoT-enabled devices to optimize energy distribution, improve grid reliability, and reduce carbon emissions.\n4. Digital Health Technologies: The convergence of electronics and healthcare will result in the development of wearable devices, medical sensors, and telemedicine platforms for remote patient monitoring, diagnosis, and treatment.\n5. Industry 4.0 Revolution: Electrical and electronics engineers will play a key role in the Industry 4.0 revolution, leveraging automation, artificial intelligence, and IoT technologies to transform manufacturing processes, enhance productivity, and enable predictive maintenance."
,        "graph": "static/graphs/EEE.PNG"
    },
    "Mechanical Engineering (ME)": {
        "insight": "1. Advanced Manufacturing Technologies: Mechanical engineers will leverage additive manufacturing, robotics, and automation to enhance production processes, reduce manufacturing costs, and improve product quality in industries such as aerospace, automotive, and consumer goods.\n2. Sustainable Design and Renewable Energy: There will be a focus on sustainable design principles, renewable energy systems, and energy-efficient technologies to address environmental challenges and minimize carbon footprint.\n3. Biomedical Engineering Innovations: ME professionals will contribute to the development of medical devices, prosthetics, and healthcare equipment through innovations in biomechanics, materials science, and bioengineering.\n4. Autonomous Vehicles and Transportation: Mechanical engineers will play a key role in the design and development of autonomous vehicles, drones, and smart transportation systems to improve safety, efficiency, and mobility.\n5. Interdisciplinary Collaboration: Collaboration with experts from diverse fields such as materials science, computer science, and environmental engineering will drive interdisciplinary innovations and solutions to complex engineering challenges."
,        "graph": "static/graphs/ME.PNG"
    },
    "Medical Technician": {
        "insight": "1. Increasing Demand for Healthcare Support Roles: The demand for medical technicians, including medical laboratory technicians, radiologic technologists, and surgical technologists, will continue to grow as healthcare services expand and technology advances.\n2. Specialized Training and Certification: Medical technicians will need specialized training and certification in their respective fields to ensure competency in performing diagnostic tests, imaging procedures, and surgical assistance.\n3. Technological Advancements in Healthcare: Medical technicians will adapt to technological advancements in healthcare, including digital imaging, laboratory automation, and telemedicine, to improve diagnostic accuracy, patient care, and treatment outcomes.\n4. Collaboration with Healthcare Professionals: Medical technicians will collaborate closely with physicians, nurses, and other healthcare professionals to provide accurate test results, assist in medical procedures, and ensure patient safety and comfort.\n5. Career Growth Opportunities: Medical technicians will have opportunities for career advancement through continuing education, specialization in niche areas, and leadership roles in healthcare organizations."
,        "graph": "static/graphs/MT.PNG"
    },
    "Electrical Engineering (EE)": {
        "insight": "1. Renewable Energy Revolution: Electrical engineers will play a crucial role in the transition towards renewable energy sources such as solar, wind, and hydroelectric power through innovations in energy generation, storage, and distribution.\n2. Grid Modernization and Smart Grids: There will be a focus on modernizing power grids and developing smart grid technologies to accommodate renewable energy integration, improve grid reliability, and enable demand response programs.\n3. Electric Vehicle Infrastructure: EE professionals will contribute to the development of electric vehicle charging infrastructure, battery technology, and grid-to-vehicle integration systems to support the widespread adoption of electric vehicles.\n4. Cybersecurity in Power Systems: With the digitization of power systems and the rise of IoT devices, there will be an increased focus on cybersecurity measures to protect critical infrastructure, prevent cyber-attacks, and ensure grid resilience.\n5. Innovations in Power Electronics: Electrical engineers will drive innovations in power electronics, including converters, inverters, and motor drives, to improve energy efficiency, reduce power losses, and enable renewable energy integration."
,        "graph": "static/graphs/EE.PNG"
    },
    "Computer Science and Engineering (CSE)": {
        "insight": "1. Continuous Growth in Tech Industry: Computer science and engineering graduates will experience steady demand in the job market, fueled by the continuous growth of the technology industry and digital transformation across sectors.\n2. Emerging Technologies and Specializations: The evolution of emerging technologies such as artificial intelligence, blockchain, and quantum computing will create new career opportunities and specialized roles for CSE professionals.\n3. Focus on Cybersecurity and Data Privacy: With increasing cyber threats and data breaches, there will be a growing demand for cybersecurity experts and data privacy specialists to safeguard digital assets and ensure regulatory compliance.\n4. Interdisciplinary Collaboration: CSE professionals will collaborate with experts from diverse fields such as healthcare finance, and environmental science to develop innovative solutions to complex societal challenges using technology.\n5. Lifelong Learning and Skill Development: Continuous learning, skill development, and adaptability will be essential for CSE graduates to stay abreast of evolving technologies, industry trends, and programming languages.",
        "graph": "static/graphs/CSE.PNG"
    }
}

